# 공통 설정은 여기서
server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  profiles:
    include:
      - properties
      - prod

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#Swagger 설정
springdoc:
  api-docs:
    path: /v1/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**
  show-login-endpoint: true #Authentication Filter login end point 제공