# 공통 설정은 여기서
server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  profiles:
    include:
      - properties
      - local
    default: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB