#각종 properties는 여기서

spring:
  config:
    activate:
      on-profile: "properties"

jwt:
  token:
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    access-expiration-time: 43200000 #12hors
    refresh-expiration-time: 604800000 #7days