#로컬 개발 설정은 여기서
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    com.bom.newsfeed: debug
    org.springframework.web.servlet: trace
    org.springframework.security: trace
    org.hibernate:
      orm.jdbc.bind: trace
      type: trace
      stat: debug

  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: false

  sql.init.mode: always

  data:
    redis:
      host: localhost
      port: 6379
